apiVersion: v1
kind: Service
metadata:
  name: grpc-server
spec:
  selector:
    app: grpc-server
  ports:
    - port: 9010
      name: http
      targetPort: http
    - port: 9030
      name: grpc-gw
      targetPort: grpc-gw
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-headless
spec:
  clusterIP: None
  selector:
    app: grpc-server
  ports:
    - port: 9020
      targetPort: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: server
          imagePullPolicy: Always
          image: registry.cn-huhehaote.aliyuncs.com/feng-566/grpc-server:v1.0.0
          args:
            - --debug
            - --db-dsn=root:password@(mysql:3306)/go-demo
          ports:
            - containerPort: 9010
              name: http
            - containerPort: 9020
              name: grpc
            - containerPort: 9030
              name: grpc-gw